chef_root = Dir.pwd

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/xenial64'

  config.vm.network :forwarded_port, guest: 443, host: 9443
  config.vm.network :forwarded_port, guest: 4002, host: 4002
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.vm.network :forwarded_port, guest: 6080, host: 6080
  config.vm.network :forwarded_port, guest: 8773, host: 8773
  config.vm.network :forwarded_port, guest: 8774, host: 8774
  config.vm.network :forwarded_port, guest: 35357, host: 35357

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = [
      "#{chef_root}/cookbooks",
      "#{chef_root}/site-cookbooks",
    ]
    chef.channel = 'stable'
    chef.version = '12.21.4'
    chef.add_role('allinone')
    chef.environment = 'allinone-ubuntu16'

    chef.data_bags_path = "#{chef_root}/data_bags"
    chef.roles_path = "#{chef_root}/roles"
    chef.environments_path = "#{chef_root}/environments"
  end

  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
    v.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
    v.customize ['modifyvm', :id, '--nicpromisc3', 'allow-all']
    v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
  end

  config.vm.define 'controller' do |c|
    c.vm.network :private_network, :type => 'dhcp', :adapter => 2
    c.vm.network :public_network, 
        :dev => 'default_bridge',
        :mode => 'bridge',
        :type => 'bridge'
  end  
end
